# Site settings
title: Swift Hacking for Fun and Profit
email: ryan@lovelett.me
description: > # this means to ignore newlines until "baseurl:"
  Guides and musings on working on and with the Swift language. Focus on Linux
  development and C bindings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rlovelett.github.io" # the base hostname & protocol for your site
twitter_username: rlovelett
github_username:  RLovelett

# Build settings
markdown: kramdown
